= CityCare - Digitale Meldestelle für städtische Mängel

== Über das Projekt
CityCare ist eine Webplattform, die es Bürgern ermöglicht, städtische Mängel wie kaputte Straßen, defekte Laternen oder Vandalismus einfach und schnell zu melden. Die Plattform erleichtert die Kommunikation mit der Stadtverwaltung und trägt dazu bei, Probleme effizienter zu lösen.

== Ziel des Projekts
Unser Hauptziel ist es, die Lebensqualität der Bürger zu verbessern, indem Probleme schneller erkannt und behoben werden. Dadurch wird die Stadtverwaltung entlastet und die Zufriedenheit der Einwohner gesteigert.

== Projektteam
- **Almina Silnovic** (Projektleitung, 3AHIF) - alminasilnovic10@gmail.com
- **Azra Özdemir** (Stellvertretung, 3AHIF) - azraozdemir@icloud.com
- **Lejla Music** (Projektmitglied, 3AHIF) - lejlamusic2409@gmail.com

== User Stories
1. **Als Bürger** möchte ich Mängel in meiner Gemeinde melden können, damit diese schnellstmöglich behoben werden.
2. **Als Gemeinde** möchte ich die gemeldeten Mängel schnell einsehen, den Bearbeitungsstatus verfolgen und gezielt Maßnahmen ergreifen können.
3. **Als Bürger** möchte ich den Status meiner Mängelmeldung verfolgen können, um zu wissen, wann und ob der Mangel bearbeitet wurde.

== Links
link:./asciidocs/docs/projektauftrag.adoc[Projektauftrag] +
link:./asciidocs/docs/pflichtenheft.adoc[Pflichtenheft] +
link:https://vm81.htl-leonding.ac.at/projects/564d6cc2-c4af-4140-825b-be13edce7dcc[Scrum Board] +

