:doctype: book
= Pflichtenheft

Azra Özdemir | Almina Silnovic | Lejla Music
{docdate}

= Beschreibung der Ausgangslage
---
== 1. Ist-Zustand
Aktuell werden Mängel in einer Gemeinde meistens telefonisch oder über Briefe bei der Stadtverwaltung gemeldet.
Diese Methode erschwert es den Bürgern ein Problem zu melden, wodurch sie generell die Motivation verlieren könnten, das Problem zu melden. Das führt dazu, dass sie unentdeckt bleiben und spät oder gar nicht gelöst werden.

== 2. Problemstellung
Die Meldung städtischer Mängel erfolgt oft über umständliche Wege (Telefon, E-Mail), was zu:

* Verzögerter Bearbeitung von Problemen
* Mangelnder Transparenz für Bürger
* Ineffizienter Verwaltung der Meldungen

führt.

== 3. Aufgabenstellung
Eine digitale Plattform soll entwickelt werden, die:

* Einfache Erfassung von Mängeln mit Foto und Standort ermöglicht
* Den Bearbeitungsstatus erfasst
* Die Verwaltung und Bearbeitung der Meldungen regelt

== 4. Zielsetzung
Unser Ziel ist es eine Plattform zu entwickeln, auf der Bürger Mängel in ihrer Gemeinde melden können. Die Meldungen sollen automatisch an die zuständige Gemeinde weitergeleitet werden, um das Problem schnellstmöglich zu lösen. Die Plattform soll benutzerfreundlich und einfach zu bedienen sein.

== 5. Anforderungen (Soll)
=== 5.1 Funktionale Anforderungen

==== Meldung von Mängeln
- Nutzer können Mängel über ein Formular melden (Beschreibung, Standort via GPS oder manuell, Foto).
- Meldungen werden kategorisiert (z.B. Straßen, Beleuchtung, Müll).
- Möglichkeit zur Registrierung oder Login mit Email und Passwort.

==== Datenverwaltung
- Nutzer können den Fortschritt der Meldung verfolgen.
- Automatische Benachrichtigungen per E-Mail bei Statusänderungen.
- Meldungen werden automatisch an die zuständige Gemeinde weitergeleitet.
- Verwaltung kann den Status der Meldung ändern und das Problem lösen.

=== 5.2 Nicht-funktionale Anforderungen

==== Benutzerfreundlichkeit
- Ansprechendes Design und einfache Nutzung, auch für technisch weniger versierte Nutzer.

==== Technische Anforderungen
- Webserver (z.B. über Github Pages) für Hosting, der Sicherheits- und Performanceanforderungen erfüllt.
- Datenbank zur Speicherung der Meldungen, die sicher und zuverlässig aufgesetzt wird.

== 6. Mengengerüst
=== 6.1 Anzahl der Benutzer
Es wird erwartet, dass 15% Benutzer die Plattform nutzen werden. Wir gehen davon aus, dass die meisten Benutzer aus Oberösterreich kommen werden.

=== 6.2 Anzahl der Meldungen
Es wird erwartet, dass die Plattform mindestens 50 Meldungen pro Monat erhält.
